### ISSUE TITLE
Cancel or suspend?

### ISSUE THREAD

**Issue by thebravoman** [fnando/paypal-recurring#24]
To stop recurring payment what should I use - cancel or suspend? I couldn't understand from the code and the guide

**Comment by RodrigoAyala** [comment]
Both will stop the recurring payment. The difference between both, is that when you suspend an account, you can reactivate it later, but when you cancel it, you can't go back and the user must authorize a new recurring payment if he regrets.

Cheers!

**Comment by thebravoman** [comment]
Thank you :)

**Comment by dws-arjun** [comment]
how do i know that payment has been suspended OR skipped? via Paypal API
