### ISSUE TITLE
Unsupported Trial period

### ISSUE THREAD

**Issue by geronimod** [fnando/paypal-recurring#3]

**Comment by rmoriz** [comment]
seems like fork:
https://github.com/jhliberty/paypal-recurring/commits/master/

has a lot of new features incl. trial period support

@fnando how about merging?

**Comment by fnando** [comment]
Done. There was a lot of broken/weird stuff, but I did some cleanup. :)

**Comment by gdiaz** [comment]
+1 ;-)
