### ISSUE TITLE
undefined method `notify_url=' for #<PayPal::Recurring::Base:0x131651bc>

### ISSUE THREAD

**Issue by datnt** [fnando/paypal-recurring#7]
Hi fnando, 

Thank you for your great gem.

I want Paypal to notify to our app whenever monthly payment occur. But when I try to add option "notify_url" I got the above issue.

Could you please give me a hint on this ?

Reference:
http://forums.devnetwork.net/viewtopic.php?f=1&t=42239
http://railscasts.com/episodes/142-paypal-notifications

**Comment by fnando** [comment]
There is no `notify_url` method. You need to use the `ipn_url` option.

``` ruby
ppr = PayPal::Recurring.new({
    :amount      => "9.00",
    :currency    => "USD",
    :description => "Awesome - Monthly Subscription",
    :ipn_url     => "http://example.com/paypal/ipn",
    :frequency   => 1,
    :token       => "EC-05C46042TU8306821",
    :period      => :monthly,
    :reference   => "1234",
    :payer_id    => "WTTS5KC2T46YU",
    :start_at    => Time.now,
    :failed      => 1,
    :outstanding => :next_billing
  })
```

## 

Nando Vieira
http://nandovieira.com.br

**Comment by datnt** [comment]
Hi

Thank you very much for your feedback.

I want to ensure that PayPal actually callback to my ipn_url. Is there any way I can test the ipn_url when I'm developing on localhost.

My ipn_url is: http://localhost:3000/payment_notifications

Thank you in advance,
Dat

**Comment by fnando** [comment]
Try using something like the [locatunnel gem](http://rubygems.org/gems/localtunnel).

## 

Nando Vieira
http://nandovieira.com.br

**Comment by datnt** [comment]
Hi  fnando,

I've set ipn_url as per your suggestion but it does not work.
1. I had check my IPN_URL by using Paypal tool and it works fine.
2. I had observed since the last comment I made a month ago to check for sure.

Thank you in advance,
Dat

**Comment by datnt** [comment]
Found a solution.

Please refer to: https://github.com/fnando/paypal-recurring/issues/10
